- name: Copy RabbitMQ file
  ansible.builtin.copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo

- name: Install RabbitmQ Server
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: installed

- name: Start RabbitMQ Service
  ansible.builtin.systemd_service:
    name: rabbitmq-server
    state: started

- name: Add application user
  ansible.builtin.shell: rabbitmqctl add_user roboshop roboshop123 ; rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"